CREATE TABLE IF NOT EXISTS cliente (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	cpf CHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);